config/routes.rb
ProyectoADDS2::Application.routes.draw do
  resources :orden_cobros

  resources :historial_octs

  resources :historial_odts

  resources :orden_trabajos

  resources :contratos

  resources :cliente_juridicos

  resources :perfils

  devise_for :users

  resources :estado_clientes

  resources :identificacions

  resources :servicios

  resources :personeria

  resources :parametros_generales

  resources :logs

  resources :estado_pagos

  resources :estado_cobros

  resources :trabajos

  resources :prioridads

  resources :estado_odts

  resources :barrios

  resources :user, :as => "users"
  
  root :to => 'perfils#index'

end

app/models/barrio.rb
class Barrio < ActiveRecord::Base
  has_many :contratos  
  validates :Nombre, :presence => true
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  acts_as_predecessor      
  #belongs_to :estado_cliente, :class_name => 'EstadoCliente', :foreign_key => :estado_cliente_id
  belongs_to :identificacion
  belongs_to :estado_cliente
  attr_accessible :email, :Direccion, :Observaciones
end

app/models/contrato.rb
class Contrato < ActiveRecord::Base
    belongs_to :cliente_juridico
    belongs_to :barrio
    belongs_to :servicio
    validates :cliente_juridico, :barrio, :servicio, :CostoInstalacion, :presence => true
    validates :CostoInstalacion, :numericality => {:greater_than => 0}
end

app/models/estado_cobro.rb
class EstadoCobro < ActiveRecord::Base
    has_many :transitions, :class_name => 'EstadoCobro', :foreign_key => :transitionCobro_id
    belongs_to :prev_state, :class_name => 'EstadoCobro', :foreign_key => :transitionCobro_id
    validates :Nombre, :presence => true
end

app/models/estado_odt.rb
class EstadoOdt < ActiveRecord::Base
    has_many :transitions, :class_name => 'EstadoOdt', :foreign_key => :transitionODT_id
    belongs_to :prev_state, :class_name => 'EstadoOdt', :foreign_key => :transitionODT_id
    validates :Nombre, :presence => true
end

app/models/estado_pago.rb
class EstadoPago < ActiveRecord::Base
    has_many :transitions, :class_name => 'EstadoPago', :foreign_key => :transitionPago_id
    belongs_to :prev_state, :class_name => 'EstadoPago', :foreign_key => :transitionPago_id

    validates :Nombre, :presence => true
end

app/models/historial.rb
class Historial < ActiveRecord::Base
acts_as_predecessor
end

app/models/historial_oct.rb
class HistorialOct < ActiveRecord::Base
	belongs_to :OrdenCobro
end

app/models/historial_odt.rb
class HistorialOdt < ActiveRecord::Base
  belongs_to :OrdenTrabajo
end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/models/orden_cobro.rb
class OrdenCobro < ActiveRecord::Base
  belongs_to :contrato
  belongs_to :estado_pagos
  belongs_to :estado_cobros
  belongs_to :user

   validates :contrato, :user, :CantidadAPagar, :presence => true
    validates :CantidadAPagar, :numericality => {:greater_than_or_equal_to => 0}
end

app/models/orden_trabajo.rb
class OrdenTrabajo < ActiveRecord::Base
  belongs_to :contrato
  belongs_to :estado_odt
  belongs_to :prioridad
  belongs_to :user

   validates :contrato, :prioridad, :user, :CantidadAPagar, :presence => true
    validates :CantidadAPagar, :numericality => {:greater_than_or_equal_to => 0}

end

app/models/perfil.rb
class Perfil < ActiveRecord::Base

    has_many :users
    has_and_belongs_to_many :permisos
end

app/models/permiso.rb
class Permiso < ActiveRecord::Base

    has_and_belongs_to_many :perfil
end

app/models/personerium.rb
class Personerium < ActiveRecord::Base
    validates :Nombre, :presence => true
    has_many :identificacions
end

app/models/prioridad.rb
class Prioridad < ActiveRecord::Base
    validates :Nombre, :presence => true
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
  has_many :contratos  
  validates :Nombre, :CostoInstalacion, :PrecioMensual, :presence => true
    validates :CostoInstalacion, :PrecioMensual,:numericality => { :greater_than => 0}
end

app/models/trabajo.rb
class Trabajo < ActiveRecord::Base
    validates :Trabajo, :presence => true
    validates
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
    attr_accessible :perfil_id, :email, :password, :password_confirmation, :remember_me, :username
    belongs_to :perfil
    
    def email_required? 
        false
    end

end

app/controllers/orden_cobros_controller.rb
class OrdenCobrosController < ApplicationController
  # GET /orden_cobros
  # GET /orden_cobros.json
  def index
    @orden_cobros = OrdenCobro.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orden_cobros }
    end
  end

  # GET /orden_cobros/1
  # GET /orden_cobros/1.json
  def show
    @orden_cobro = OrdenCobro.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @orden_cobro }
    end
  end

  # GET /orden_cobros/new
  # GET /orden_cobros/new.json
  def new
    @orden_cobro = OrdenCobro.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @orden_cobro }
    end
  end

  # GET /orden_cobros/1/edit
  def edit
    @orden_cobro = OrdenCobro.find(params[:id])
  end

  # POST /orden_cobros
  # POST /orden_cobros.json
  def create
    @orden_cobro = OrdenCobro.new(params[:orden_cobro])

    respond_to do |format|
      if @orden_cobro.save
        format.html { redirect_to @orden_cobro, notice: 'Orden cobro was successfully created.' }
        format.json { render json: @orden_cobro, status: :created, location: @orden_cobro }
      else
        format.html { render action: "new" }
        format.json { render json: @orden_cobro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orden_cobros/1
  # PUT /orden_cobros/1.json
  def update
    @orden_cobro = OrdenCobro.find(params[:id])

    respond_to do |format|
      if @orden_cobro.update_attributes(params[:orden_cobro])
        format.html { redirect_to @orden_cobro, notice: 'Orden cobro was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @orden_cobro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orden_cobros/1
  # DELETE /orden_cobros/1.json
  def destroy
    @orden_cobro = OrdenCobro.find(params[:id])
    @orden_cobro.destroy

    respond_to do |format|
      format.html { redirect_to orden_cobros_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/orden_cobros_helper.rb
module OrdenCobrosHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/orden_cobros/_form.html.erb
<%= form_for(@orden_cobro) do |f| %>
  <% if @orden_cobro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@orden_cobro.errors.count, "error") %> prohibited this orden_cobro from being saved:</h2>

      <ul>
      <% @orden_cobro.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :FechaPago %><br />
    <%= f.date_select :FechaPago %>
  </div>
  <div class="field">
    <%= f.label :CantidadAPagar %><br />
    <%= f.text_field :CantidadAPagar %>
  </div>
  <div class="field">
    <%= f.label :NumRecibo %><br />
    <%= f.text_field :NumRecibo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orden_cobros/edit.html.erb
<h1>Editing orden_cobro</h1>

<%= render 'form' %>

<%= link_to 'Show', @orden_cobro %> |
<%= link_to 'Back', orden_cobros_path %>

app/views/orden_cobros/index.html.erb
<h1>Listing orden_cobros</h1>

<table>
  <tr>
    <th>Fechapago</th>
    <th>Cantidadapagar</th>
    <th>Numrecibo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orden_cobros.each do |orden_cobro| %>
  <tr>
    <td><%= orden_cobro.FechaPago %></td>
    <td><%= orden_cobro.CantidadAPagar %></td>
    <td><%= orden_cobro.NumRecibo %></td>
    <td><%= link_to 'Show', orden_cobro %></td>
    <td><%= link_to 'Edit', edit_orden_cobro_path(orden_cobro) %></td>
    <td><%= link_to 'Destroy', orden_cobro, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Orden cobro', new_orden_cobro_path %>

app/views/orden_cobros/new.html.erb
<h1>New orden_cobro</h1>

<%= render 'form' %>

<%= link_to 'Back', orden_cobros_path %>

app/views/orden_cobros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Fechapago:</b>
  <%= @orden_cobro.FechaPago %>
</p>

<p>
  <b>Cantidadapagar:</b>
  <%= @orden_cobro.CantidadAPagar %>
</p>

<p>
  <b>Numrecibo:</b>
  <%= @orden_cobro.NumRecibo %>
</p>


<%= link_to 'Edit', edit_orden_cobro_path(@orden_cobro) %> |
<%= link_to 'Back', orden_cobros_path %>