config/routes.rb
ProyectoADDS2::Application.routes.draw do
  resources :orden_cobros

  resources :historial_octs

  resources :historial_odts

  resources :orden_trabajos

  resources :contratos

  resources :cliente_juridicos

  resources :perfils

  devise_for :users

  resources :estado_clientes

  resources :identificacions

  resources :servicios

  resources :personeria

  resources :parametros_generales

  resources :logs

  resources :estado_pagos

  resources :estado_cobros

  resources :trabajos

  resources :prioridads

  resources :estado_odts

  resources :barrios

  resources :user, :as => "users"
  
  root :to => 'perfils#index'

end

app/models/barrio.rb
class Barrio < ActiveRecord::Base
  has_many :contratos  
  validates :Nombre, :presence => true
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  acts_as_predecessor      
  #belongs_to :estado_cliente, :class_name => 'EstadoCliente', :foreign_key => :estado_cliente_id
  belongs_to :identificacion
  belongs_to :estado_cliente
  attr_accessible :email, :Direccion, :Observaciones
end

app/models/contrato.rb
class Contrato < ActiveRecord::Base
    belongs_to :cliente_juridico
    belongs_to :barrio
    belongs_to :servicio
    validates :cliente_juridico, :barrio, :servicio, :CostoInstalacion, :presence => true
    validates :CostoInstalacion, :numericality => {:greater_than => 0}
end

app/models/estado_cobro.rb
class EstadoCobro < ActiveRecord::Base
    has_many :transitions, :class_name => 'EstadoCobro', :foreign_key => :transitionCobro_id
    belongs_to :prev_state, :class_name => 'EstadoCobro', :foreign_key => :transitionCobro_id
    validates :Nombre, :presence => true
end

app/models/estado_odt.rb
class EstadoOdt < ActiveRecord::Base
    has_many :transitions, :class_name => 'EstadoOdt', :foreign_key => :transitionODT_id
    belongs_to :prev_state, :class_name => 'EstadoOdt', :foreign_key => :transitionODT_id
    validates :Nombre, :presence => true
end

app/models/estado_pago.rb
class EstadoPago < ActiveRecord::Base
    has_many :transitions, :class_name => 'EstadoPago', :foreign_key => :transitionPago_id
    belongs_to :prev_state, :class_name => 'EstadoPago', :foreign_key => :transitionPago_id

    validates :Nombre, :presence => true
end

app/models/historial.rb
class Historial < ActiveRecord::Base
acts_as_predecessor
end

app/models/historial_oct.rb
class HistorialOct < ActiveRecord::Base
	belongs_to :OrdenCobro
end

app/models/historial_odt.rb
class HistorialOdt < ActiveRecord::Base
  belongs_to :OrdenTrabajo
end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/models/orden_cobro.rb
class OrdenCobro < ActiveRecord::Base
  belongs_to :contrato
  belongs_to :estado_pagos
  belongs_to :estado_cobros
  belongs_to :user

   validates :contrato, :user, :CantidadAPagar, :presence => true
    validates :CantidadAPagar, :numericality => {:greater_than_or_equal_to => 0}
end

app/models/orden_trabajo.rb
class OrdenTrabajo < ActiveRecord::Base
  belongs_to :contrato
  belongs_to :estado_odt
  belongs_to :prioridad
  belongs_to :user

   validates :contrato, :prioridad, :user, :CantidadAPagar, :presence => true
    validates :CantidadAPagar, :numericality => {:greater_than_or_equal_to => 0}

end

app/models/perfil.rb
class Perfil < ActiveRecord::Base

    has_many :users
    has_and_belongs_to_many :permisos
end

app/models/permiso.rb
class Permiso < ActiveRecord::Base

    has_and_belongs_to_many :perfil
end

app/models/personerium.rb
class Personerium < ActiveRecord::Base
    validates :Nombre, :presence => true
    has_many :identificacions
end

app/models/prioridad.rb
class Prioridad < ActiveRecord::Base
    validates :Nombre, :presence => true
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
  has_many :contratos  
  validates :Nombre, :CostoInstalacion, :PrecioMensual, :presence => true
    validates :CostoInstalacion, :PrecioMensual,:numericality => { :greater_than => 0}
end

app/models/trabajo.rb
class Trabajo < ActiveRecord::Base
    validates :Trabajo, :presence => true
    validates
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
    attr_accessible :perfil_id, :email, :password, :password_confirmation, :remember_me, :username
    belongs_to :perfil
    
    def email_required? 
        false
    end

end

app/controllers/servicios_controller.rb
class ServiciosController < ApplicationController
  # GET /servicios
  # GET /servicios.json
before_filter :authenticate_user!, :except => [:index]
  def index
    @servicios = Servicio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @servicios }
    end
  end

  # GET /servicios/1
  # GET /servicios/1.json
  def show
    @servicio = Servicio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @servicio }
    end
  end

  # GET /servicios/new
  # GET /servicios/new.json
  def new
    @servicio = Servicio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @servicio }
    end
  end

  # GET /servicios/1/edit
  def edit
    @servicio = Servicio.find(params[:id])
  end

  # POST /servicios
  # POST /servicios.json
  def create
    @servicio = Servicio.new(params[:servicio])

    respond_to do |format|
      if @servicio.save
        format.html { redirect_to @servicio, notice: 'Servicio was successfully created.' }
        format.json { render json: @servicio, status: :created, location: @servicio }
      else
        format.html { render action: "new" }
        format.json { render json: @servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /servicios/1
  # PUT /servicios/1.json
  def update
    @servicio = Servicio.find(params[:id])

    respond_to do |format|
      if @servicio.update_attributes(params[:servicio])
        format.html { redirect_to @servicio, notice: 'Servicio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servicios/1
  # DELETE /servicios/1.json
  def destroy
    @servicio = Servicio.find(params[:id])
    @servicio.destroy

    respond_to do |format|
      format.html { redirect_to servicios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/servicios/_form.html.erb
<%SimpleForm.browser_validations = false%>
<%=simple_form_for @servicio do |f| %>
   <p><%= f.input :Nombre %></p>
   <p><%= f.input :CostoInstalacion %></p>
   <p><%= f.input :PrecioMensual %></p>
   <p><%= f.input :Descripcion %> </p>
   <%= f.button :submit %>
<% end %>

app/views/servicios/edit.html.erb
<h1>Editing servicio</h1>

<%= render 'form' %>

  <%= link_to 'Show', @servicio %> |
<%= link_to 'Back', servicios_path %>

app/views/servicios/index.html.erb
<h1>Listing servicios</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Costoinstalacion</th>
    <th>Preciomensual</th>
    <th>Descripcion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @servicios.each do |servicio| %>
  <tr>
    <td><%= servicio.Nombre %></td>
    <td><%= servicio.CostoInstalacion %></td>
    <td><%= servicio.PrecioMensual %></td>
    <td><%= servicio.Descripcion %></td>
  
        <td><%= link_to 'Show', servicio %></td>

        <td><%= link_to 'Edit', edit_servicio_path(servicio) %></td>

    <td><%= link_to 'Destroy', servicio, confirm: 'Are you sure?', method: :delete %></td>
 
  </tr>
<% end %>
</table>

<br />

  <%= link_to 'New Servicio', new_servicio_path %>

app/views/servicios/new.html.erb
<h1>New servicio</h1>

<%= render 'form' %>

<%= link_to 'Back', servicios_path %>

app/views/servicios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @servicio.Nombre %>
</p>

<p>
  <b>Costoinstalacion:</b>
  <%= @servicio.CostoInstalacion %>
</p>

<p>
  <b>Preciomensual:</b>
  <%= @servicio.PrecioMensual %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @servicio.Descripcion %>
</p>


<%= link_to 'Edit', edit_servicio_path(@servicio) %> |

<%= link_to 'Back', servicios_path %>