config/routes.rb
ProyectoADDS2::Application.routes.draw do
  resources :orden_cobros

  resources :historial_octs

  resources :historial_odts

  resources :orden_trabajos

  resources :contratos

  resources :cliente_juridicos

  resources :perfils

  devise_for :users

  resources :estado_clientes

  resources :identificacions

  resources :servicios

  resources :personeria

  resources :parametros_generales

  resources :logs

  resources :estado_pagos

  resources :estado_cobros

  resources :trabajos

  resources :prioridads

  resources :estado_odts

  resources :barrios

  resources :user, :as => "users"
  
  root :to => 'perfils#index'

end

app/models/barrio.rb
class Barrio < ActiveRecord::Base
  has_many :contratos  
  validates :Nombre, :presence => true
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  acts_as_predecessor      
  #belongs_to :estado_cliente, :class_name => 'EstadoCliente', :foreign_key => :estado_cliente_id
  belongs_to :identificacion
  belongs_to :estado_cliente
  attr_accessible :email, :Direccion, :Observaciones
end

app/models/contrato.rb
class Contrato < ActiveRecord::Base
    belongs_to :cliente_juridico
    belongs_to :barrio
    belongs_to :servicio
    validates :cliente_juridico, :barrio, :servicio, :CostoInstalacion, :presence => true
    validates :CostoInstalacion, :numericality => {:greater_than => 0}
end

app/models/estado_cliente.rb
  class EstadoCliente < ActiveRecord::Base
    has_many :transitions, :class_name => 'EstadoCliente', :foreign_key => :transitionCliente_id
    belongs_to :prev_state, :class_name => 'EstadoCliente', :foreign_key => :transitionCliente_id
    has_many :cliente_juridicos
    validates :Nombre, :presence => true
    
end

app/models/estado_cobro.rb
class EstadoCobro < ActiveRecord::Base
    has_many :transitions, :class_name => 'EstadoCobro', :foreign_key => :transitionCobro_id
    belongs_to :prev_state, :class_name => 'EstadoCobro', :foreign_key => :transitionCobro_id
    validates :Nombre, :presence => true
end

app/models/estado_odt.rb
class EstadoOdt < ActiveRecord::Base
    has_many :transitions, :class_name => 'EstadoOdt', :foreign_key => :transitionODT_id
    belongs_to :prev_state, :class_name => 'EstadoOdt', :foreign_key => :transitionODT_id
    validates :Nombre, :presence => true
end

app/models/estado_pago.rb
class EstadoPago < ActiveRecord::Base
    has_many :transitions, :class_name => 'EstadoPago', :foreign_key => :transitionPago_id
    belongs_to :prev_state, :class_name => 'EstadoPago', :foreign_key => :transitionPago_id

    validates :Nombre, :presence => true
end

app/models/historial.rb
class Historial < ActiveRecord::Base
acts_as_predecessor
end

app/models/historial_oct.rb
class HistorialOct < ActiveRecord::Base
	belongs_to :OrdenCobro
end

app/models/historial_odt.rb
class HistorialOdt < ActiveRecord::Base
  belongs_to :OrdenTrabajo
end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/models/orden_cobro.rb
class OrdenCobro < ActiveRecord::Base
  belongs_to :contrato
  belongs_to :estado_pagos
  belongs_to :estado_cobros
  belongs_to :user

   validates :contrato, :user, :CantidadAPagar, :presence => true
    validates :CantidadAPagar, :numericality => {:greater_than_or_equal_to => 0}
end

app/models/orden_trabajo.rb
class OrdenTrabajo < ActiveRecord::Base
  belongs_to :contrato
  belongs_to :estado_odt
  belongs_to :prioridad
  belongs_to :user

   validates :contrato, :prioridad, :user, :CantidadAPagar, :presence => true
    validates :CantidadAPagar, :numericality => {:greater_than_or_equal_to => 0}

end

app/models/perfil.rb
class Perfil < ActiveRecord::Base

    has_many :users
    has_and_belongs_to_many :permisos
end

app/models/permiso.rb
class Permiso < ActiveRecord::Base

    has_and_belongs_to_many :perfil
end

app/models/personerium.rb
class Personerium < ActiveRecord::Base
    validates :Nombre, :presence => true
    has_many :identificacions
end

app/models/prioridad.rb
class Prioridad < ActiveRecord::Base
    validates :Nombre, :presence => true
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
  has_many :contratos  
  validates :Nombre, :CostoInstalacion, :PrecioMensual, :presence => true
    validates :CostoInstalacion, :PrecioMensual,:numericality => { :greater_than => 0}
end

app/models/trabajo.rb
class Trabajo < ActiveRecord::Base
    validates :Trabajo, :presence => true
    validates
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
    attr_accessible :perfil_id, :email, :password, :password_confirmation, :remember_me, :username
    belongs_to :perfil
    
    def email_required? 
        false
    end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
# before_filter :authenticate_user!, :except => [:index]
 # before_filter :validate_admin

  def validate_admin
    if !user_signed_in? || current_user.perfil.Nombre =! "Administrador"
	
	redirect_to root_path
    else
      current_user.perfil.Nombre = "Administrador"
    end
  end
 
  def index
    if user_signed_in? && current_user.perfil.Nombre == "Administrador"  
        @users = User.all
        respond_to do |format|
            format.html # index.html.erb
            format.json { render json: @users }
        end
    else
        redirect_to root_path
    end
  end
    
  def show
      @user = User.find(params[:id])

      respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end
    
  def update
    @user = User.find(params[:id])
    respond_to do |format|
       if @user.update_attributes(params[:user])
         format.html { redirect_to @user, notice: 'Barrio was successfully updated.' }
         format.json { head :no_content }
       else
         format.html { render action: "edit" }
         format.json { render json: @user.errors, status: :unprocessable_entity }
       end
    end
  end

  def destroy
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/edit.html.erb
<h1> Editando usuarios </h1>

<%= simple_form_for @user do |f| %>
    <!--<%= f.error_notification %>-->

   <div class="inputs">
       <%= f.input :username, :required => true, :autofocus => true %>
       <%= f.input :email %>
       <%= f.input :password, :required => true %>
                     
       <%= f.input :password_confirmation, :required => true %>
       <%= f.association :perfil, :collection => Perfil.all ,:label_method => :Nombre,  :label => "Seleccione un perfil: " %>
                             
   </div>
   <div class="actions">
       <%= f.button :submit, "Sign up" %>
   </div>
<% end %>

<%= link_to 'Show', @user %> | <%= link_to 'Back', users_path %>

app/views/user/index.html.erb
<h1>User#index</h1>

<table>
  <tr>
    <th>Username
    <th>Email</th>
    <th>Perfil</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <% if current_user.id != user.id%>
    <td><%= user.username%></td>
    <td><%= user.email %></td>
    <td><%= user.perfil.Nombre %></td>
    <td> <%= link_to 'Show', user_path(user) %>
    <td><%= link_to 'Edit', edit_user_path(user)%></td>
    <%end%>
  </tr>
<% end %>
</table>

app/views/user/new.html.erb
<h2>New User</h2>

<%= simple_form_for @user do |f| %>
  <!--<%= f.error_notification %>-->

  <div class="inputs">
    <%= f.input :username, :required => true, :autofocus => true %>
    <%= f.input :email %>
    <%= f.input :password, :required => true %>
    
    <%= f.input :password_confirmation, :required => true %>
    <%= f.association :perfil, :collection => Perfil.all ,:label_method => :Nombre,  :label => "Seleccione un perfil: " %>
   
  </div>

  <div class="actions">
    <%= f.button :submit, "Sign up" %>
  </div>
<% end %>

app/views/user/show.html.erb
<h1>Mostrando Perfil:</h1>
    <p>
        <b> Username: </b>
        <%= @user.username %>
    </p>

    <p>
        <b>Email: </b>
        <%= @user.email %>
    </p>
    <p>
        <b>Perfil: </b>
        <%= @user.perfil.Nombre %>
    </p>

    <%= link_to 'Edit', edit_user_path(@user)%> | <%= link_to 'Back', users_path%>