config/routes.rb
ProyectoADDS2::Application.routes.draw do
  resources :orden_cobros

  resources :historial_octs

  resources :historial_odts

  resources :orden_trabajos

  resources :contratos

  resources :cliente_juridicos

  resources :perfils

  devise_for :users

  resources :estado_clientes

  resources :identificacions

  resources :servicios

  resources :personeria

  resources :parametros_generales

  resources :logs

  resources :estado_pagos

  resources :estado_cobros

  resources :trabajos

  resources :prioridads

  resources :estado_odts

  resources :barrios

  resources :user, :as => "users"
  
  root :to => 'perfils#index'

end

app/models/barrio.rb
class Barrio < ActiveRecord::Base
  has_many :contratos  
  validates :Nombre, :presence => true
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  acts_as_predecessor      
  #belongs_to :estado_cliente, :class_name => 'EstadoCliente', :foreign_key => :estado_cliente_id
  belongs_to :identificacion
  belongs_to :estado_cliente
  attr_accessible :email, :Direccion, :Observaciones
end

app/models/cliente_juridico.rb
class ClienteJuridico < ActiveRecord::Base
  acts_as_heir_of :cliente  
 # attr_accessible :NombreEmpresa, :Cargo, :Responsable, :fax, :identificacion_id, :estado_cliente_id
  has_many :contratos
  belongs_to :identificacion
  belongs_to :estado_cliente
  validates :identificacion, :numeroIdentificacion, :NombreEmpresa, :Cargo, :Responsable, :estado_cliente, :presence => true
  def Nombre
    self.NombreEmpresa
  end
end

app/models/contrato.rb
class Contrato < ActiveRecord::Base
    belongs_to :cliente_juridico
    belongs_to :barrio
    belongs_to :servicio
    validates :cliente_juridico, :barrio, :servicio, :CostoInstalacion, :presence => true
    validates :CostoInstalacion, :numericality => {:greater_than => 0}
end

app/models/estado_cobro.rb
class EstadoCobro < ActiveRecord::Base
    has_many :transitions, :class_name => 'EstadoCobro', :foreign_key => :transitionCobro_id
    belongs_to :prev_state, :class_name => 'EstadoCobro', :foreign_key => :transitionCobro_id
    validates :Nombre, :presence => true
end

app/models/estado_odt.rb
class EstadoOdt < ActiveRecord::Base
    has_many :transitions, :class_name => 'EstadoOdt', :foreign_key => :transitionODT_id
    belongs_to :prev_state, :class_name => 'EstadoOdt', :foreign_key => :transitionODT_id
    validates :Nombre, :presence => true
end

app/models/estado_pago.rb
class EstadoPago < ActiveRecord::Base
    has_many :transitions, :class_name => 'EstadoPago', :foreign_key => :transitionPago_id
    belongs_to :prev_state, :class_name => 'EstadoPago', :foreign_key => :transitionPago_id

    validates :Nombre, :presence => true
end

app/models/historial.rb
class Historial < ActiveRecord::Base
acts_as_predecessor
end

app/models/historial_oct.rb
class HistorialOct < ActiveRecord::Base
	belongs_to :OrdenCobro
end

app/models/historial_odt.rb
class HistorialOdt < ActiveRecord::Base
  belongs_to :OrdenTrabajo
end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/models/orden_cobro.rb
class OrdenCobro < ActiveRecord::Base
  belongs_to :contrato
  belongs_to :estado_pagos
  belongs_to :estado_cobros
  belongs_to :user

   validates :contrato, :user, :CantidadAPagar, :presence => true
    validates :CantidadAPagar, :numericality => {:greater_than_or_equal_to => 0}
end

app/models/perfil.rb
class Perfil < ActiveRecord::Base

    has_many :users
    has_and_belongs_to_many :permisos
end

app/models/permiso.rb
class Permiso < ActiveRecord::Base

    has_and_belongs_to_many :perfil
end

app/models/personerium.rb
class Personerium < ActiveRecord::Base
    validates :Nombre, :presence => true
    has_many :identificacions
end

app/models/prioridad.rb
class Prioridad < ActiveRecord::Base
    validates :Nombre, :presence => true
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
  has_many :contratos  
  validates :Nombre, :CostoInstalacion, :PrecioMensual, :presence => true
    validates :CostoInstalacion, :PrecioMensual,:numericality => { :greater_than => 0}
end

app/models/trabajo.rb
class Trabajo < ActiveRecord::Base
    validates :Trabajo, :presence => true
    validates
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
    attr_accessible :perfil_id, :email, :password, :password_confirmation, :remember_me, :username
    belongs_to :perfil
    
    def email_required? 
        false
    end

end

app/controllers/cliente_juridicos_controller.rb
class ClienteJuridicosController < ApplicationController
  # GET /cliente_juridicos
  # GET /cliente_juridicos.json
  def index
    @cliente_juridicos = ClienteJuridico.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cliente_juridicos }
    end
  end

  # GET /cliente_juridicos/1
  # GET /cliente_juridicos/1.json
  def show
    @cliente_juridico = ClienteJuridico.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cliente_juridico }
    end
  end

  # GET /cliente_juridicos/new
  # GET /cliente_juridicos/new.json
  def new
    @cliente_juridico = ClienteJuridico.new
    @personeria = Personerium.where('Nombre = "Juridica"')
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cliente_juridico }
    end
  end

  # GET /cliente_juridicos/1/edit
  def edit
    @cliente_juridico = ClienteJuridico.find(params[:id])
  end

  # POST /cliente_juridicos
  # POST /cliente_juridicos.json
  def create
    @personeria = Personerium.where('Nombre = "Juridica"')
    @cliente_juridico = ClienteJuridico.new(params[:cliente_juridico])

    respond_to do |format|
      if @cliente_juridico.save
        format.html { redirect_to @cliente_juridico, notice: 'Cliente juridico was successfully created.' }
        format.json { render json: @cliente_juridico, status: :created, location: @cliente_juridico }
      else
        format.html { render action: "new" }
        format.json { render json: @cliente_juridico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cliente_juridicos/1
  # PUT /cliente_juridicos/1.json
  def update
    @cliente_juridico = ClienteJuridico.find(params[:id])

    respond_to do |format|
      if @cliente_juridico.update_attributes(params[:cliente_juridico])
        format.html { redirect_to @cliente_juridico, notice: 'Cliente juridico was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cliente_juridico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cliente_juridicos/1
  # DELETE /cliente_juridicos/1.json
  def destroy
    @cliente_juridico = ClienteJuridico.find(params[:id])
    @cliente_juridico.destroy

    respond_to do |format|
      format.html { redirect_to cliente_juridicos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cliente_juridicos_helper.rb
module ClienteJuridicosHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cliente_juridicos/_form.html.erb
<%= simple_form_for @cliente_juridico do |f| %>
  <div class = "inputs">
      <%= f.association :identificacion, :collection => Identificacion.all, :label_method => :TipoIdentificacion, :label => "Identificacion: " %>
      <%= f.input :numeroIdentificacion %>
      <%= f.input :NombreEmpresa %>
      <%= f.input :Cargo %>
      <%= f.input :Responsable %>
      <%= f.input :fax %>
      <%= f.input :email %>
      <%= f.input :Direccion%>
      <%= f.association :estado_cliente, :collection => EstadoCliente.all, :label_method => :Nombre, :label => "Estado de Cliente: " %>
      <%= f.input :Observaciones %>
      <%= f.button :submit %>
      
    </div>
<%end%>

app/views/cliente_juridicos/edit.html.erb
<h1>Editing cliente_juridico</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente_juridico %> |
<%= link_to 'Back', cliente_juridicos_path %>

app/views/cliente_juridicos/index.html.erb
<h1>Listing cliente_juridicos</h1>

<table>
  <tr>
    <th>Nombreempresa</th>
    <th>Cargo</th>
    <th>Responsable</th>
    <th>Fax</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cliente_juridicos.each do |cliente_juridico| %>
  <tr>
    <td><%= cliente_juridico.NombreEmpresa %></td>
    <td><%= cliente_juridico.Cargo %></td>
    <td><%= cliente_juridico.Responsable %></td>
    <td><%= cliente_juridico.fax %></td>
    <td><%= link_to 'Show', cliente_juridico %></td>
    <td><%= link_to 'Edit', edit_cliente_juridico_path(cliente_juridico) %></td>
    <td><%= link_to 'Destroy', cliente_juridico, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cliente juridico', new_cliente_juridico_path %>

app/views/cliente_juridicos/new.html.erb
<h1>New cliente_juridico</h1>

<%= render 'form' %>

<%= link_to 'Back', cliente_juridicos_path %>

app/views/cliente_juridicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombreempresa:</b>
  <%= @cliente_juridico.NombreEmpresa %>
</p>

<p>
  <b>Cargo:</b>
  <%= @cliente_juridico.Cargo %>
</p>

<p>
  <b>Responsable:</b>
  <%= @cliente_juridico.Responsable %>
</p>

<p>
  <b>Fax:</b>
  <%= @cliente_juridico.fax %>
</p>


<%= link_to 'Edit', edit_cliente_juridico_path(@cliente_juridico) %> |
<%= link_to 'Back', cliente_juridicos_path %>